packages:
  - frontend/*
  - frontend/products/*
  - frontend/mobile/*
  - backend/*
  - backend/products/*
  - backend/workers/*
  - packages/*

catalogMode: strict

minimumReleaseAge: 720

minimumReleaseAgeExclude:
  - turbo

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  prisma: true

catalog:
  react-markdown: 10.1.0
  remark-gfm: 4.0.1
