import type { MetadataRoute } from 'next';

// Web app manifest: name, colors, and icons for "Add to home screen" (generated by scripts/generate-images.sh).
export const dynamic = 'force-static';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Oxinov',
    short_name: 'Oxinov',
    description: 'Oxinov builds software, services, and research for people everywhere.',
    start_url: '/',
    display: 'browser',
    lang: 'en',
    background_color: '#07070D',
    theme_color: '#07070D',
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
      { src: '/icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
}
