import {
  cut,
  cutCorners,
  fonts,
  gradientSignature,
  lineHeight,
  motion,
  space,
  themes,
  typeScale,
  type ThemeColors,
} from './tokens.js';

const kebab = (name: string): string => name.replace(/[A-Z0-9]+/g, (part) => `-${part.toLowerCase()}`);

function colorVariables(colors: ThemeColors): string[] {
  const lines: string[] = [];
  for (const [name, value] of Object.entries(colors)) {
    if (typeof value === 'string') lines.push(`--ox-color-${kebab(name)}: ${value};`);
  }
  for (const [product, value] of Object.entries(colors.product)) {
    lines.push(`--ox-color-product-${product}: ${value};`);
  }
  return lines;
}

function block(selector: string, lines: string[], indent = ''): string {
  return `${indent}${selector} {\n${lines.map((line) => `${indent}  ${line}`).join('\n')}\n${indent}}`;
}

/** Renders every token as CSS custom properties with dark default, Daylight theme, and motion rules. */
export function renderTokensCss(): string {
  const shared = [
    `--ox-font-display: ${fonts.display};`,
    `--ox-font-heading: ${fonts.heading};`,
    `--ox-font-body: ${fonts.body};`,
    `--ox-font-mono: ${fonts.mono};`,
    ...typeScale.map((size, index) => `--ox-text-${index}: ${size}rem;`),
    `--ox-leading-body: ${lineHeight.body};`,
    `--ox-leading-heading: ${lineHeight.heading};`,
    ...space.map((size, index) => `--ox-space-${index + 1}: ${size}px;`),
    `--ox-cut-sm: ${cutCorners(cut.sm)};`,
    `--ox-cut-md: ${cutCorners(cut.md)};`,
    `--ox-gradient-signature: ${gradientSignature};`,
    `--ox-duration-fast: ${motion.fastMs}ms;`,
    `--ox-duration-base: ${motion.baseMs}ms;`,
    `--ox-duration-glow: ${motion.glowMs}ms;`,
    `--ox-duration-glitch: ${motion.glitchMs}ms;`,
    `--ox-easing: ${motion.easing};`,
    // Glow is built from the brand color so it follows the active theme.
    '--ox-glow-brand: 0 0 6px color-mix(in srgb, var(--ox-color-brand) 60%, transparent), 0 0 18px color-mix(in srgb, var(--ox-color-brand) 25%, transparent);',
    '--ox-focus-ring: 0 0 0 2px var(--ox-color-bg), 0 0 0 4px var(--ox-color-focus);',
    '--ox-grid-background: linear-gradient(var(--ox-color-grid) 1px, transparent 1px), linear-gradient(90deg, var(--ox-color-grid) 1px, transparent 1px);',
    '--ox-grid-size: 32px 32px;',
  ];

  return [
    '/* Generated by @oxinov/design-system from src/tokens.ts. Do not edit by hand. */',
    block(':root', [...shared, 'color-scheme: dark;', ...colorVariables(themes.dark)]),
    block(':root[data-theme="light"]', ['color-scheme: light;', ...colorVariables(themes.light)]),
    // The Daylight theme follows the device setting until the person picks a theme.
    `@media (prefers-color-scheme: light) {\n${block(':root:not([data-theme="dark"])', ['color-scheme: light;', ...colorVariables(themes.light)], '  ')}\n}`,
    // Reduced motion turns off every animation and transition, including glitch and glow pulses.
    `@media (prefers-reduced-motion: reduce) {\n${block(':root', ['--ox-duration-fast: 0ms;', '--ox-duration-base: 0ms;', '--ox-duration-glow: 0ms;', '--ox-duration-glitch: 0ms;'], '  ')}\n${block('*, *::before, *::after', ['animation-duration: 0.01ms !important;', 'animation-iteration-count: 1 !important;', 'transition-duration: 0.01ms !important;', 'scroll-behavior: auto !important;'], '  ')}\n}`,
    '',
  ].join('\n\n');
}
