"""Generate/check the requested project library inventory (NFR-12 maintainability)."""
from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path, PurePosixPath
import subprocess

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = "docs/08-engineering/file-catalog.md"
AREAS = {
    ".claude": "Agent launch configuration and assistant skills", ".github": "CI and collaboration",
    "backend": "APIs and workers", "database": "Schemas, migrations, policies and seeds",
    "devops": "Infrastructure and delivery", "docs": "Requirements and operating guides",
    "frontend": "Company, portal and product interfaces", "monitoring": "Metrics and alerts",
    "packages": "Shared libraries", "prompts": "Milestone instructions",
    "scripts": "Repository maintenance", "security": "Security and incident response",
}
RESERVED = {
    "backend/products/edu-chat", "backend/gateway", "backend/products/edu-worker", "backend/workers/platform-worker",
    "devops/ansible", "frontend/mobile", "packages/auth", "packages/config",
    "packages/contracts", "packages/domain", "packages/observability",
    "packages/security-events", "packages/testing",
}


def inventory(root: Path = ROOT) -> list[str]:
    result = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"],
        cwd=root, check=True, stdout=subprocess.PIPE,
    )
    paths = set(result.stdout.decode("utf-8").split("\0"))
    return sorted({p for p in paths if p and (root / p).is_file()} | {OUTPUT},
                  key=lambda p: (p.casefold(), p))


def _service_paths() -> set[str]:
    try:
        from service_catalog import load
        return {s["path"] for s in load()["services"].values()}
    except (ImportError, OSError, ValueError, KeyError):
        return set()


def state(folder: str) -> str:
    if folder in _service_paths():
        return "Deployable service registered in services.yaml (see docs/08-engineering/service-catalog.md)."
    if folder in RESERVED:
        return "Reserved / planned; not an implemented application."
    if folder in {"backend/products", "database/products", "frontend/products", "docs/02-products"}:
        return "Product shelf: one folder per product slug (see docs/02-products/README.md)."
    return "Repository content; consult its owning README for implementation status."


def role(path: str) -> str:
    name = PurePosixPath(path).name
    if name.endswith((".spec.ts", ".e2e-spec.ts", ".test.ts", ".test.mjs", ".test.sh")) or name.startswith("test_"):
        return "Test / verification"
    if name == "README.md":
        return "Folder guide"
    if name.endswith(".md"):
        return "Documentation"
    if name.endswith(".example"):
        return "Configuration example"
    if name == "migration.sql":
        return "Ordered database migration"
    for suffix, description in {
        ".sql": "Database policy, seed or check", ".prisma": "Database schema",
        ".controller.ts": "API routes", ".service.ts": "Server-side service",
        ".dto.ts": "API contract", ".tf": "Infrastructure definition",
        ".tftpl": "Infrastructure template",
    }.items():
        if name.endswith(suffix):
            return description
    if name in {"page.tsx", "route.ts"}:
        return "Web route"
    if name.endswith((".svg", ".jpg", ".png")):
        return "Visual asset"
    if name.endswith((".sh", ".py")) or name == "oxctl":
        return "Automation / maintenance"
    if name.endswith((".ts", ".tsx", ".js", ".mjs", ".css")):
        return "Source / tooling"
    return "Configuration / supporting file"


def render(paths: list[str]) -> str:
    folders: dict[str, list[str]] = defaultdict(list)
    for path in paths:
        parent = PurePosixPath(path).parent
        folders[str(parent)].append(path)
        while str(parent) != ".":
            parent = parent.parent
            folders.setdefault(str(parent), [])
    ordered = sorted(folders, key=lambda p: (p != ".", p.casefold(), p))
    anchors = {folder: f"folder-{i}" for i, folder in enumerate(ordered)}
    lines = [
        "# Project file catalog", "",
        "[Project library](../../PROJECT-LIBRARY.md) · [Placement rules](project-structure.md) · [Documentation map](../README.md)", "",
        "Complete repository inventory: category, folder, then filename alphabetically.",
        "Generated by `python scripts/project_catalog.py`; edit the generator, not individual entries.",
        "Includes tracked and non-ignored new files present on disk. Excludes ignored local files and empty folders.",
        "Only paths are inventoried, never file contents. Counts are not measures of feature completion.", "",
        f"**{len(paths)} files · {len(folders) - 1} folders**, plus repository root.", "",
        "## Categories", "", "| Category | Purpose | Files |", "| --- | --- | ---: |",
        f"| [Root](#{anchors['.']}) | Entry points and workspace configuration | {len(folders['.'])} |",
    ]
    for area in sorted({p.split('/')[0] for p in paths if '/' in p}, key=str.casefold):
        count = sum(p.startswith(area + '/') for p in paths)
        lines.append(f"| [{area}/](#{anchors[area]}) | {AREAS.get(area, 'Repository support')} | {count} |")
    lines += ["", "## Folder directory", "", "Use Find to search a full path or filename. Grouping folders are included.", ""]
    for folder in ordered:
        lines.append(f"- [{folder}/](#{anchors[folder]})")
    lines += ["", "## Files by folder", ""]
    for folder in ordered:
        lines += [f'<a id="{anchors[folder]}"></a>', "", f"### {folder}/", "", state(folder), ""]
        children = [p for p in ordered if p != "." and str(PurePosixPath(p).parent) == folder]
        if children:
            lines += ["Subfolders: " + " · ".join(f"[{PurePosixPath(p).name}/](#{anchors[p]})" for p in children), ""]
        if folders[folder]:
            lines += ["| File | Role |", "| --- | --- |"]
            for path in sorted(folders[folder], key=lambda p: (p.casefold(), p)):
                label = PurePosixPath(path).name.replace('[', '\\[').replace(']', '\\]')
                target = '../../' + path.replace(' ', '%20')
                lines.append(f"| [{label}]({target}) | {role(path)} |")
            lines.append("")
        lines += ["[Back to directory](#folder-directory)", ""]
    return '\n'.join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(inventory())
    destination = ROOT / OUTPUT
    if args.check:
        if not destination.is_file() or destination.read_text(encoding="utf-8") != expected:
            print("ERROR: Catalog stale. Run: python scripts/project_catalog.py")
            return 1
        print("Project file catalog is current")
    else:
        destination.write_text(expected, encoding="utf-8", newline="\n")
        print(f"Updated {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
